// Microsoft Fluent Emoji manifest - categories and emoji names
// Emojis are loaded from GitHub CDN: https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/

export interface FluentEmojiCategory {
  name: string;
  folder: string;
  emojis: string[];
}

export const FLUENT_EMOJI_BASE_URL =
  "https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis";

export const fluentEmojiCategories: FluentEmojiCategory[] = [
  {
    name: "Smilies",
    folder: "Smilies",
    emojis: [
      "Grinning Face",
      "Grinning Face with Big Eyes",
      "Grinning Face with Smiling Eyes",
      "Beaming Face with Smiling Eyes",
      "Grinning Squinting Face",
      "Grinning Face with Sweat",
      "Rolling on the Floor Laughing",
      "Face with Tears of Joy",
      "Slightly Smiling Face",
      "Winking Face",
      "Smiling Face with Smiling Eyes",
      "Smiling Face with Halo",
      "Smiling Face with Hearts",
      "Smiling Face with Heart-Eyes",
      "Star-Struck",
      "Face Blowing a Kiss",
      "Kissing Face",
      "Smiling Face",
      "Kissing Face with Closed Eyes",
      "Kissing Face with Smiling Eyes",
      "Smiling Face with Tear",
      "Face Savoring Food",
      "Face with Tongue",
      "Winking Face with Tongue",
      "Zany Face",
      "Squinting Face with Tongue",
      "Money-Mouth Face",
      "Hugging Face",
      "Shushing Face",
      "Thinking Face",
      "Zipper-Mouth Face",
      "Face with Raised Eyebrow",
      "Neutral Face",
      "Expressionless Face",
      "Face Without Mouth",
      "Smirking Face",
      "Unamused Face",
      "Face with Rolling Eyes",
      "Grimacing Face",
      "Lying Face",
      "Relieved Face",
      "Pensive Face",
      "Sleepy Face",
      "Drooling Face",
      "Sleeping Face",
      "Face with Medical Mask",
      "Face with Thermometer",
      "Face with Head-Bandage",
      "Nauseated Face",
      "Face Vomiting",
      "Sneezing Face",
      "Hot Face",
      "Cold Face",
      "Woozy Face",
      "Dizzy Face",
      "Exploding Head",
      "Cowboy Hat Face",
      "Partying Face",
      "Disguised Face",
      "Smiling Face with Sunglasses",
      "Nerd Face",
      "Face with Monocle",
      "Confused Face",
      "Worried Face",
      "Slightly Frowning Face",
      "Frowning Face",
      "Face with Open Mouth",
      "Hushed Face",
      "Astonished Face",
      "Flushed Face",
      "Pleading Face",
      "Frowning Face with Open Mouth",
      "Anguished Face",
      "Fearful Face",
      "Anxious Face with Sweat",
      "Sad but Relieved Face",
      "Crying Face",
      "Loudly Crying Face",
      "Face Screaming in Fear",
      "Confounded Face",
      "Persevering Face",
      "Disappointed Face",
      "Downcast Face with Sweat",
      "Weary Face",
      "Tired Face",
      "Yawning Face",
      "Face with Steam From Nose",
      "Angry Face",
      "Enraged Face",
      "Smiling Face with Horns",
      "Angry Face with Horns",
      "Skull",
      "Skull and Crossbones",
      "Pile of Poo",
      "Clown Face",
      "Ogre",
      "Goblin",
      "Ghost",
      "Alien",
      "Alien Monster",
      "Robot",
      "Red Heart",
      "Orange Heart",
      "Yellow Heart",
      "Green Heart",
      "Blue Heart",
      "Purple Heart",
      "Black Heart",
      "Broken Heart",
      "Heart on Fire",
      "Sparkling Heart",
      "Growing Heart",
      "Beating Heart",
      "Revolving Hearts",
      "Two Hearts",
      "Heart Decoration",
      "Heart Exclamation",
      "Love Letter",
      "Kiss Mark",
      "Hundred Points",
    ],
  },
  {
    name: "Hand Gestures",
    folder: "Hand gestures",
    emojis: [
      "Waving Hand",
      "Raised Back of Hand",
      "Hand with Fingers Splayed",
      "Raised Hand",
      "Vulcan Salute",
      "OK Hand",
      "Pinched Fingers",
      "Pinching Hand",
      "Victory Hand",
      "Crossed Fingers",
      "Love-You Gesture",
      "Sign of the Horns",
      "Call Me Hand",
      "Backhand Index Pointing Left",
      "Backhand Index Pointing Right",
      "Backhand Index Pointing Up",
      "Middle Finger",
      "Backhand Index Pointing Down",
      "Index Pointing Up",
      "Thumbs Up",
      "Thumbs Down",
      "Raised Fist",
      "Oncoming Fist",
      "Left-Facing Fist",
      "Right-Facing Fist",
      "Clapping Hands",
      "Raising Hands",
      "Open Hands",
      "Palms Up Together",
      "Handshake",
      "Folded Hands",
      "Writing Hand",
      "Nail Polish",
      "Selfie",
      "Flexed Biceps",
    ],
  },
  {
    name: "Animals",
    folder: "Animals",
    emojis: [
      "Dog Face",
      "Cat Face",
      "Mouse Face",
      "Hamster",
      "Rabbit Face",
      "Fox",
      "Bear",
      "Panda",
      "Koala",
      "Tiger Face",
      "Lion",
      "Cow Face",
      "Pig Face",
      "Pig Nose",
      "Frog",
      "Monkey Face",
      "See-No-Evil Monkey",
      "Hear-No-Evil Monkey",
      "Speak-No-Evil Monkey",
      "Monkey",
      "Chicken",
      "Penguin",
      "Bird",
      "Baby Chick",
      "Hatching Chick",
      "Front-Facing Baby Chick",
      "Duck",
      "Eagle",
      "Owl",
      "Bat",
      "Wolf",
      "Boar",
      "Horse Face",
      "Unicorn",
      "Honeybee",
      "Bug",
      "Butterfly",
      "Snail",
      "Lady Beetle",
      "Ant",
      "Mosquito",
      "Cockroach",
      "Spider",
      "Spider Web",
      "Scorpion",
      "Turtle",
      "Snake",
      "Lizard",
      "T-Rex",
      "Sauropod",
      "Octopus",
      "Squid",
      "Shrimp",
      "Lobster",
      "Crab",
      "Blowfish",
      "Tropical Fish",
      "Fish",
      "Dolphin",
      "Whale",
      "Spouting Whale",
      "Shark",
      "Crocodile",
    ],
  },
  {
    name: "Food",
    folder: "Food",
    emojis: [
      "Grapes",
      "Melon",
      "Watermelon",
      "Tangerine",
      "Lemon",
      "Banana",
      "Pineapple",
      "Mango",
      "Red Apple",
      "Green Apple",
      "Pear",
      "Peach",
      "Cherries",
      "Strawberry",
      "Kiwi Fruit",
      "Tomato",
      "Coconut",
      "Avocado",
      "Eggplant",
      "Potato",
      "Carrot",
      "Ear of Corn",
      "Hot Pepper",
      "Cucumber",
      "Leafy Green",
      "Broccoli",
      "Garlic",
      "Onion",
      "Mushroom",
      "Peanuts",
      "Chestnut",
      "Bread",
      "Croissant",
      "Baguette Bread",
      "Pancakes",
      "Waffle",
      "Cheese Wedge",
      "Meat on Bone",
      "Poultry Leg",
      "Cut of Meat",
      "Bacon",
      "Hamburger",
      "French Fries",
      "Pizza",
      "Hot Dog",
      "Sandwich",
      "Taco",
      "Burrito",
      "Cooking",
      "Pot of Food",
      "Bowl with Spoon",
      "Spaghetti",
      "Sushi",
      "Bento Box",
      "Curry Rice",
      "Rice Ball",
      "Rice",
      "Rice Cracker",
      "Fish Cake with Swirl",
      "Moon Cake",
      "Dango",
      "Dumpling",
      "Fortune Cookie",
      "Takeout Box",
      "Crab",
      "Lobster",
      "Oyster",
      "Soft Ice Cream",
      "Shaved Ice",
      "Ice Cream",
      "Doughnut",
      "Cookie",
      "Birthday Cake",
      "Shortcake",
      "Cupcake",
      "Pie",
      "Chocolate Bar",
      "Candy",
      "Lollipop",
      "Custard",
      "Honey Pot",
      "Baby Bottle",
      "Glass of Milk",
      "Hot Beverage",
      "Teacup Without Handle",
      "Sake",
      "Champagne",
      "Wine Glass",
      "Cocktail Glass",
      "Tropical Drink",
      "Beer Mug",
      "Clinking Beer Mugs",
      "Clinking Glasses",
      "Tumbler Glass",
    ],
  },
  {
    name: "Activities",
    folder: "Activities",
    emojis: [
      "Jack-O-Lantern",
      "Christmas Tree",
      "Fireworks",
      "Sparkler",
      "Firecracker",
      "Sparkles",
      "Balloon",
      "Party Popper",
      "Confetti Ball",
      "Tanabata Tree",
      "Pine Decoration",
      "Japanese Dolls",
      "Carp Streamer",
      "Wind Chime",
      "Moon Viewing Ceremony",
      "Red Envelope",
      "Ribbon",
      "Wrapped Gift",
      "Trophy",
      "Sports Medal",
      "1st Place Medal",
      "2nd Place Medal",
      "3rd Place Medal",
      "Soccer Ball",
      "Baseball",
      "Softball",
      "Basketball",
      "Volleyball",
      "American Football",
      "Rugby Football",
      "Tennis",
      "Flying Disc",
      "Bowling",
      "Cricket Game",
      "Field Hockey",
      "Ice Hockey",
      "Lacrosse",
      "Ping Pong",
      "Badminton",
      "Boxing Glove",
      "Martial Arts Uniform",
      "Goal Net",
      "Flag in Hole",
      "Ice Skate",
      "Fishing Pole",
      "Running Shirt",
      "Skis",
      "Sled",
      "Direct Hit",
      "Pool 8 Ball",
      "Video Game",
      "Slot Machine",
      "Game Die",
      "Puzzle Piece",
      "Chess Pawn",
      "Performing Arts",
      "Artist Palette",
    ],
  },
  {
    name: "Travel & Places",
    folder: "Travel and places",
    emojis: [
      "Globe Showing Europe-Africa",
      "Globe Showing Americas",
      "Globe Showing Asia-Australia",
      "Globe with Meridians",
      "World Map",
      "Map of Japan",
      "Compass",
      "Snow-Capped Mountain",
      "Mountain",
      "Volcano",
      "Mount Fuji",
      "Camping",
      "Beach with Umbrella",
      "Desert",
      "Desert Island",
      "National Park",
      "Stadium",
      "Classical Building",
      "Building Construction",
      "House",
      "House with Garden",
      "Office Building",
      "Post Office",
      "Hospital",
      "Bank",
      "Hotel",
      "Love Hotel",
      "Convenience Store",
      "School",
      "Department Store",
      "Factory",
      "Japanese Castle",
      "Castle",
      "Wedding",
      "Tokyo Tower",
      "Statue of Liberty",
      "Church",
      "Mosque",
      "Synagogue",
      "Fountain",
      "Tent",
      "Foggy",
      "Night with Stars",
      "Cityscape",
      "Sunrise Over Mountains",
      "Sunrise",
      "Cityscape at Dusk",
      "Sunset",
      "Bridge at Night",
      "Carousel Horse",
      "Ferris Wheel",
      "Roller Coaster",
      "Locomotive",
      "Railway Car",
      "High-Speed Train",
      "Bullet Train",
      "Train",
      "Metro",
      "Light Rail",
      "Station",
      "Tram",
      "Monorail",
      "Mountain Railway",
      "Tram Car",
      "Bus",
      "Oncoming Bus",
      "Trolleybus",
      "Minibus",
      "Ambulance",
      "Fire Engine",
      "Police Car",
      "Oncoming Police Car",
      "Taxi",
      "Oncoming Taxi",
      "Automobile",
      "Oncoming Automobile",
      "Sport Utility Vehicle",
      "Delivery Truck",
      "Articulated Lorry",
      "Tractor",
      "Racing Car",
      "Motorcycle",
      "Motor Scooter",
      "Bicycle",
      "Kick Scooter",
      "Airplane",
      "Small Airplane",
      "Airplane Departure",
      "Airplane Arrival",
      "Helicopter",
      "Rocket",
      "Flying Saucer",
      "Sun",
      "Full Moon",
      "Star",
      "Glowing Star",
      "Shooting Star",
      "Cloud",
      "Sun Behind Cloud",
      "Cloud with Lightning and Rain",
      "Rainbow",
      "Umbrella",
      "Snowflake",
      "Comet",
      "Fire",
      "Droplet",
      "Water Wave",
    ],
  },
  {
    name: "Objects",
    folder: "Objects",
    emojis: [
      "Glasses",
      "Sunglasses",
      "Goggles",
      "Lab Coat",
      "T-Shirt",
      "Jeans",
      "Scarf",
      "Gloves",
      "Coat",
      "Socks",
      "Dress",
      "Kimono",
      "Bikini",
      "Running Shoe",
      "High-Heeled Shoe",
      "Crown",
      "Top Hat",
      "Graduation Cap",
      "Ring",
      "Clutch Bag",
      "Briefcase",
      "Backpack",
      "Laptop",
      "Desktop Computer",
      "Keyboard",
      "Computer Mouse",
      "Trackball",
      "Joystick",
      "Clamp",
      "Computer Disk",
      "Floppy Disk",
      "Optical Disk",
      "DVDs",
      "Abacus",
      "Movie Camera",
      "Film Frames",
      "Film Projector",
      "Clapper Board",
      "Television",
      "Camera",
      "Camera with Flash",
      "Video Camera",
      "Videocassette",
      "Magnifying Glass Tilted Left",
      "Magnifying Glass Tilted Right",
      "Candle",
      "Light Bulb",
      "Flashlight",
      "Red Paper Lantern",
      "Notebook",
      "Closed Book",
      "Open Book",
      "Green Book",
      "Blue Book",
      "Orange Book",
      "Books",
      "Bookmark",
      "Scroll",
      "Clipboard",
      "Newspaper",
      "Rolled-up Newspaper",
      "Page with Curl",
      "Bookmark Tabs",
      "Calendar",
      "Tear-Off Calendar",
      "Card Index",
      "Chart Increasing",
      "Chart Decreasing",
      "Chart",
      "Card File Box",
      "File Cabinet",
      "Wastebasket",
      "Locked",
      "Unlocked",
      "Key",
      "Hammer",
      "Axe",
      "Hammer and Pick",
      "Nut and Bolt",
      "Gear",
      "Link",
      "Chains",
      "Magnet",
      "Gem Stone",
      "Money Bag",
      "Dollar Banknote",
      "Credit Card",
      "Hourglass Done",
      "Watch",
      "Alarm Clock",
      "Stopwatch",
      "Timer Clock",
      "Telephone",
      "Mobile Phone",
      "Battery",
      "Electric Plug",
      "Envelope",
      "Envelope with Arrow",
      "Bell",
      "Crystal Ball",
      "Musical Keyboard",
      "Guitar",
      "Violin",
      "Drum",
      "Microphone",
      "Headphone",
      "Loudspeaker",
    ],
  },
  {
    name: "Symbols",
    folder: "Symbols",
    emojis: [
      "Heart with Arrow",
      "Heart with Ribbon",
      "Sparkling Heart",
      "Two Hearts",
      "Heart Decoration",
      "Heart Exclamation",
      "Broken Heart",
      "Red Heart",
      "Orange Heart",
      "Yellow Heart",
      "Green Heart",
      "Blue Heart",
      "Purple Heart",
      "Black Heart",
      "White Heart",
      "Hundred Points",
      "Anger Symbol",
      "Speech Balloon",
      "Thought Balloon",
      "Zzz",
      "Musical Note",
      "Musical Notes",
      "Plus",
      "Minus",
      "Multiply",
      "Divide",
      "Infinity",
      "Double Exclamation Mark",
      "Exclamation Question Mark",
      "Question Mark",
      "White Question Mark",
      "White Exclamation Mark",
      "Exclamation Mark",
      "Warning",
      "Check Mark Button",
      "Check Mark",
      "Cross Mark",
      "Cross Mark Button",
      "Curly Loop",
      "Double Curly Loop",
      "Part Alternation Mark",
      "Eight-Spoked Asterisk",
      "Eight-Pointed Star",
      "Sparkle",
      "Copyright",
      "Registered",
      "Trade Mark",
    ],
  },
];

// Helper to get the URL for an emoji
export function getFluentEmojiUrl(folder: string, emojiName: string): string {
  const encodedName = encodeURIComponent(emojiName);
  return `${FLUENT_EMOJI_BASE_URL}/${encodeURIComponent(folder)}/${encodedName}.png`;
}

// Get all emojis flattened with their metadata
export function getAllFluentEmojis(): Array<{
  name: string;
  category: string;
  folder: string;
}> {
  const emojis: Array<{ name: string; category: string; folder: string }> = [];
  for (const category of fluentEmojiCategories) {
    for (const emoji of category.emojis) {
      emojis.push({
        name: emoji,
        category: category.name,
        folder: category.folder,
      });
    }
  }
  return emojis;
}
